# Generated by Django 2.0.5 on 2018-05-31 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ncompras', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('idPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.persona'),
        ),
    ]
