# Generated by Django 2.0.5 on 2018-06-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
