# Generated by Django 2.0.5 on 2018-06-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180607_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultaInt',
            fields=[
                ('idCon', models.IntegerField(primary_key=True, serialize=False)),
                ('NombreLe', models.CharField(max_length=50)),
                ('Ap', models.CharField(max_length=50)),
                ('Am', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Tel', models.CharField(max_length=15)),
                ('Dir', models.CharField(max_length=80)),
                ('EscP', models.CharField(max_length=80)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.libros')),
            ],
        ),
        migrations.AlterField(
            model_name='lector',
            name='Idl',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
